// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IComponentDuplexFields {
  /** Internal name */
  internalName?: string | undefined;

  /** Headline */
  headline?: string | undefined;
}

/** Full-width container for displaying side-by-side image and copy, includes multiple layout options */

export interface IComponentDuplex extends Entry<IComponentDuplexFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentDuplex";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentHeroBannerFields {
  /** Internal name */
  internalName?: string | undefined;

  /** Headline */
  headline?: string | undefined;

  /** Body text */
  bodyText?: Document | undefined;
}

/** Full-width container for displaying images and snappy copy; can include an optional CTA */

export interface IComponentHeroBanner
  extends Entry<IComponentHeroBannerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentHeroBanner";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IComponentQuoteFields {
  /** Internal name */
  internalName?: string | undefined;

  /** title */
  title: string;
}

/** Module for not found page */

export interface IComponentQuote extends Entry<IComponentQuoteFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "componentQuote";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IFooterMenuFields {
  /** Internal name */
  internalName?: string | undefined;

  /** Name */
  name: string;
}

/** Navigation content type used for powering the Footer menu */

export interface IFooterMenu extends Entry<IFooterMenuFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "footerMenu";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IPageFields {
  /** Internal name */
  internalName: string;

  /** Page name */
  pageName?: string | undefined;

  /** Slug */
  slug: string;

  /** Modules */
  modules?: (IComponentHeroBanner | IComponentQuote)[] | undefined;

  /** footer */
  footer: IFooterMenu;

  /** header */
  header: IComponentDuplex;
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "page";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE =
  | "componentDuplex"
  | "componentHeroBanner"
  | "componentQuote"
  | "footerMenu"
  | "page";

export type IEntry =
  | IComponentDuplex
  | IComponentHeroBanner
  | IComponentQuote
  | IFooterMenu
  | IPage;

export type LOCALE_CODE = "en-US" | "es";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
